# Generated by Django 5.0.4 on 2024-04-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitors",
                to="app1.coordinator",
            ),
        ),
    ]
