# Generated by Django 5.0.4 on 2024-05-02 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_alter_coordinator_phone_alter_visitor_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visitor",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
