# Generated by Django 5.0.4 on 2024-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_visitor_created_visitor_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitor",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AddField(
            model_name="visitor",
            name="phone",
            field=models.CharField(default=1232323233, max_length=15),
            preserve_default=False,
        ),
    ]
